### ISSUE TITLE
feat: instant unstake using jup.ag

### ISSUE THREAD

**Issue by f8122dac91** [igneous-labs/stake-pool-sdk#43]
- package: @jup-ag/core
 - reference: https://docs.jup.ag/jupiter-core/using-jupiter-core

---

 - Add support for token swap (scnSOL -> SOL) using [jupiter aggregator](https://jup.ag/)
 - Should expose a top-level method `withdrawStakeInstant` in `Socean` class

### Considerations:
 - Should consider changing `withdrawStake` -> `withdrawStakeDelayed` since:
   - makes it clear how these are different
   - better for us if people use swap instead of unstaking directly and `withdrawStake` might make it look like the default

**Comment by billythedummy** [comment]
i feel like this doesnt need to be part of this library. If we do this we need to constantly maintain the jup-ag versions as well
