### ISSUE TITLE
fix: WithdrawStake method returns Transaction too large error

### ISSUE THREAD

**Issue by f8122dac91** [igneous-labs/stake-pool-sdk#73]
>reported by Step Finance

Call to `withdrawStake` on mainnet results in:
```
Error: Transaction too large: 1326 > 1232
```

**Comment by billythedummy** [comment]
https://github.com/igneous-labs/stake-pool-sdk/commit/8ec54759f8a303a29553ec1814a107dc4c4d3c0f should fix it
