### ISSUE TITLE
BUG: instanceof connection returns false in next-js 

### ISSUE THREAD

**Issue by billythedummy** [igneous-labs/stake-pool-sdk#75]
```
const { connection } = useConnection();
const socean = useMemo(() => new Socean(network, connection), [network, connection]);
```

since `connectionOption instanceof Connection` returns false from this line^, the constructor interprets the connection object as a string instead, and throws `TypeError [ERR_INVALID_URL]: Invalid URL`

**Comment by sayantank** [comment]
How would I replicate this? I tried using the `useSocean()` hook and it seemed to be working fine

![image](https://user-images.githubusercontent.com/40912636/159411881-3496d98f-ce77-4c2a-accb-0d49b4803656.png)

**Comment by billythedummy** [comment]
change line 14 of SoceanProvider from 
`const socean = useMemo(() => new Socean(cluster.network), [cluster.network]);`

to 

`const socean = useMemo(() => new Socean(network, connection), [network, connection]);`

**Comment by sayantank** [comment]
This is pretty weird, the only way I've been able to correctly check if its a `Connection` instance is using `connection.constructor.name === "Connection"`. But I guess that would validate any class named `Connection`.

Even this returns false,
```
// eslint-disable-next-line no-prototype-builtins
console.log(Connection.prototype.isPrototypeOf(connection));
```

Reference:
https://stackoverflow.com/questions/1249531/how-to-get-a-javascript-objects-class
